import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Poppins, Noto_Sans } from 'next/font/google'

const poppins = Poppins({ 
  weight: ['400', '900'],
  subsets: ['latin'],
 })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
